### ISSUE TITLE
如果自己要集成原生插件怎么集成？

### ISSUE THREAD

**Issue by kang558** [kuaifan/weiui#11]
#### 如果自己要集成原生插件怎么集成？
比如，一个toast插件。
能给个集成的示例demo嘛 ？

**Comment by kuaifan** [comment]
即将出插件化，感谢支持

**Comment by kang558** [comment]
> 即将出插件化，感谢支持

非常给力啊，写一个怎么封装插件的教程啊

**Comment by kuaifan** [comment]
插件开发教程https://weiui.cc/plugin/dev/create.html
