### ISSUE TITLE
为啥我老是创建项目一直卡，都半个小时没反应了...

### ISSUE THREAD

**Issue by gdoudeng** [kuaifan/weiui#12]
![avatar](http://iplus-studio.top/Snipaste_2019-02-11_20-55-41.png)

**Comment by gdoudeng** [comment]
没人理我一下下吗...

**Comment by kuaifan** [comment]
安装的包在github，大约有80M，没有科学上网的的确有点慢，后期再想想其他办法。

**Comment by kuaifan** [comment]
框架已经插件化，现在包只有14M左右，搭建好以后需要什么功能再通过脚手架添加即可
