### ISSUE TITLE
怎么创建一个页面并做跳转

### ISSUE THREAD

**Issue by kang558** [kuaifan/weiui#13]
怎么创建一个页面并做跳转，文档里面也没说
并且这个新页面怎么支持热更新？
如图：我创建的新页面，怎么跳转过去打开，需不需要配置路由之类的？
![image](https://user-images.githubusercontent.com/22288837/56586354-281dd900-6612-11e9-8867-e5ea79893714.png)

**Comment by kuaifan** [comment]
//示例①
const weiui = weex.requireModule('weiui');
weiui.openPage({
    url: 'mine',
}, function(result) {
    //......
});

//示例②
const weiui = weex.requireModule('weiui');
weiui.openPage({
    pageName: 'pageName_1',
    pageType: 'weex',
    url: 'mine'
}, function(result) {
    //......
});

//示例③
const navigator = weex.requireModule('navigator');
navigator.push({
    url: 'mine'
}, function(result) {
    //......
});


示例①、示例②详情：https://weiui.app/module/newPage.html#weiui-openpage
示例③详情：https://weiui.app/module/navigator.html#navigator-push

**Comment by kang558** [comment]
不需要配置路由？这只是跳转啊

**Comment by kuaifan** [comment]
不需要，路由自动生成的，你只需要再次 npm run dev 或者 npm run build

**Comment by kang558** [comment]
> ```js
> //示例①
> const weiui = weex.requireModule('weiui');
> weiui.openPage({
>     url: 'mine',
> }, function(result) {
>     //......
> });
> 
> //示例②
> const weiui = weex.requireModule('weiui');
> weiui.openPage({
>     pageName: 'pageName_1',
>     pageType: 'weex',
>     url: 'mine'
> }, function(result) {
>     //......
> });
> 
> //示例③
> const navigator = weex.requireModule('navigator');
> navigator.push({
>     url: 'mine'
> }, function(result) {
>     //......
> });
> ```
> 
> 示例①、示例②详情：https://weiui.app/module/newPage.html#weiui-openpage
> 示例③详情：https://weiui.app/module/navigator.html#navigator-push
