### ISSUE TITLE
保存图片没有申请权限，导致保存失败【bug】

### ISSUE THREAD

**Issue by kang558** [kuaifan/weiui#14]
我只测了安卓的，还有就是能否保存到指定的目录，就是传一个路径的参数，APP外层的路径（或者默认保存到相册）
``
weiui.saveImage(url, callback(result))
``
[https://weiui.app/module/saveImage.html#weiui-saveimage](https://weiui.app/module/saveImage.html#weiui-saveimage)

**Comment by kuaifan** [comment]
希望提供一下机型及安卓版本号方便测试

**Comment by kang558** [comment]
> 希望提供一下机型及安卓版本号方便测试
没有提示申请读写内存权限，保存返回 succeed 但去图库确找不到图片
小米note3， Android8.1.0

**Comment by kuaifan** [comment]
最新版本已修复，详情：
https://github.com/kuaifan/weiui/releases/tag/0.0.40

升级主程序最新版本可直接使用weiui update升级，详情：
https://weiui.app/guide/update.html
