### ISSUE TITLE
更新的zip文件包括哪些文件，直接打包修改的vue文件吗还是整个项目都打包

### ISSUE THREAD

**Issue by UncleJoker** [kuaifan/weiui#15]

**Comment by kang558** [comment]
你是说热更新吗？热更新直接打包build出来的 js 文件

**Comment by UncleJoker** [comment]
> 热更新直接打包build出来的 j

那我改了一个vue文件，只要打包那个vue文件，上传到后台就行了吧

**Comment by kang558** [comment]
这个我不太清楚，但是我都是直接打包整个build出来的js文件的

**Comment by UncleJoker** [comment]
> 这个我不太清楚，但是我都是直接打包整个build出来的js文件的

然后把这个压缩包上传到管理中心就会自动更新了吧

**Comment by kang558** [comment]
是的

**Comment by UncleJoker** [comment]
> 是的

dist这个文件夹一起压缩吗

**Comment by kang558** [comment]
不是，dist文件夹下选中所有文件，打包成zip

**Comment by UncleJoker** [comment]
> 不是，dist文件夹下选中所有文件，打包成zip

好的，请问在项目里执行weiui build生产js文件吗？我用weiui build 命令，结果把js文件直接打包到xcode里都不用热更新

**Comment by kang558** [comment]
npm run build

**Comment by UncleJoker** [comment]
> npm run build

老哥。我按照步骤执行了，为啥不提示更新？难道还要配置其他东西吗

**Comment by kang558** [comment]
![image](https://user-images.githubusercontent.com/22288837/58310912-57567e80-7e3a-11e9-92a2-a4eed36781e7.png)

**Comment by UncleJoker** [comment]
![屏幕快照 2019-05-24 下午3 41 56](https://user-images.githubusercontent.com/12726955/58310972-7f45e200-7e3a-11e9-9d04-76b2e9eb863c.png)

**Comment by UncleJoker** [comment]
我用的是模拟器的

**Comment by kang558** [comment]
版本对应上没有啊

**Comment by UncleJoker** [comment]
> 版本对应上没有啊

xcode上的app版本1.0，更新版本要比他高吗

**Comment by UncleJoker** [comment]
![屏幕快照 2019-05-24 下午3 46 37](https://user-images.githubusercontent.com/12726955/58311264-2165ca00-7e3b-11e9-8b04-250685f83896.png)

**Comment by kang558** [comment]
就是这样的啊，你的压缩包怎么打的。先把热刷新断掉，还有你APP重启之后有更新到吗？

**Comment by UncleJoker** [comment]
> 就是这样的啊，你的压缩包怎么打的。先把热刷新断掉，还有你APP重启之后有更新到吗？

热刷新怎么断掉的

**Comment by kang558** [comment]
我也忘记了，你直接卸载掉重新run试试

**Comment by UncleJoker** [comment]
好的

**Comment by UncleJoker** [comment]
![屏幕快照 2019-05-24 下午3 58 49](https://user-images.githubusercontent.com/12726955/58311961-d51b8980-7e3c-11e9-98a2-29959b2de8b1.png)

**Comment by UncleJoker** [comment]
要在info.plist添加remote-notification这个吗？

**Comment by kang558** [comment]
估计吧，我没更新过iOS版  :joy:  或者问一下他 @kuaifan

**Comment by kuaifan** [comment]
> > 热更新直接打包build出来的 j
> 
> 那我改了一个vue文件，只要打包那个vue文件生成的js文件，上传到后台就行了吧

【那我改了一个vue文件，只要打包那个vue文件生成的js文件】对的，只打包上传修改的文件即可，当然也可以把所有js文件都打包上传。

**Comment by kuaifan** [comment]
> remote-notification

这个应该是推送通知用的。
