### ISSUE TITLE
这个框架还不错，什么时候出ios的版本，不然ios 还要单独开发，失去用weex意义了

### ISSUE THREAD

**Issue by shaibaoj** [kuaifan/weiui#2]
这个框架还不错，什么时候出ios的版本，不然ios 还要单独开发，失去用weex意义了

**Comment by JamesBLTG** [comment]
很喜欢你们的安卓版，对于初学者有很大的意义，请问下，ios版本什么时候出来？可以有swift版本的吗

**Comment by zhuewizz** [comment]
这个框架，我见过目前最好的，支持，有赞助的地方吗？

**Comment by kuaifan** [comment]
谢谢支持 😂 😂 😂
