### ISSUE TITLE
error: attribute 'com.nio.pm.portal.mobile:srcCompat' not found 编译引入报错

### ISSUE THREAD

**Issue by guoquancaho** [kuaifan/weiui#5]
error: attribute 'com.nio.pm.portal.mobile:srcCompat' not found.
Message{kind=ERROR, text=error: attribute 'com.nio.pm.portal.mobile:srcCompat' not found., sources=[/Users/quanchao.guo/.gradle/caches/transforms-1/files-1.1/weiui-0.0.22.aar/4ca13e37ae3bce7727540b39e75b0d40/res/layout/dialog_ad.xml], original message=, tool name=Optional.of(AAPT)}

**Comment by kuaifan** [comment]
clean gradle
